### ISSUE TITLE
sm_block does not show the message from phrases.txt

### ISSUE THREAD

**Issue by deprid** [Dosergen/Stuff#1]
Previously I used Bara version 1.0.0 and when I tested it, it showed the message along with the annoying 'F*K U' message.

Just now I tried your version 1.0.1 and it just showed this (without the message):
```
] sm plugins
To see more, type "sm plugins 11"
```
Could you fix it?

**Comment by Dosergen** [comment]
Thank you for your attention. Fixed it.

**Comment by deprid** [comment]
Thanks for the quick fix, just tested it, now it's working fine...
